[project]
name = "pytrade2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ibapi>=9.81.1.post1",
    "lxml>=6.0.2",
    "pyqt6>=6.10.0",
    "python-dotenv>=1.2.1",
    "selenium>=4.40.0",
    "setuptools>=80.10.2",
    "undetected-chromedriver>=3.5.5",
    "webdriver-manager>=4.0.2",
    "yfinance>=0.2.66",
]
